countries_extra = {
    "ABW": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "AFG": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "AGO": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "AIA": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "ALA": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "ALB": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "AND": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "ARE": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "ARG": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "ARM": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "ASM": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "ATA": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "ATF": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "ATG": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "AUS": {"has_other_symbols": False, "has_cross": True, "has_star": True, "is_triband": False},
    "AUT": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "AZE": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": True},
    "BDI": {"has_other_symbols": False, "has_cross": True, "has_star": True, "is_triband": False},
    "BEL": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "BEN": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "BES": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "BFA": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "BGD": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "BGR": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "BHR": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "BHS": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "BIH": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "BLM": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "BLR": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "BLZ": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "BMU": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "BOL": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "BRA": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "BRB": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "BRN": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "BTN": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "BVT": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "BWA": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "CAF": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "CAN": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "CCK": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "CHE": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "CHL": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "CHN": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "CIV": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "CMR": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "COD": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "COG": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "COK": {"has_other_symbols": False, "has_cross": True, "has_star": True, "is_triband": False},
    "COL": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "COM": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "CPV": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "CRI": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "CUB": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "CUW": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "CXR": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "CYM": {"has_other_symbols": True, "has_cross": True, "has_star": True, "is_triband": False},
    "CYP": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "CZE": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "DEU": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "DJI": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "DMA": {"has_other_symbols": True, "has_cross": True, "has_star": True, "is_triband": False},
    "DNK": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "DOM": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "DZA": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "ECU": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "EGY": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "ERI": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "ESH": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": True},
    "ESP": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": True},
    "EST": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "ETH": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "FIN": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "FJI": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "FLK": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "FRA": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "FRO": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "FSM": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "GAB": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "GBR": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "GEO": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "GGY": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "GHA": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "GIB": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "GIN": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "GLP": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "GMB": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "GNB": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "GNQ": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": True},
    "GRC": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "GRD": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "GRL": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "GTM": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "GUF": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "GUM": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "GUY": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "HKG": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "HMD": {"has_other_symbols": False, "has_cross": True, "has_star": True, "is_triband": False},
    "HND": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "HRV": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": True},
    "HTI": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "HUN": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "IDN": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "IMN": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "IND": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "IOT": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "IRL": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "IRN": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "IRQ": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "ISL": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "ISR": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "ITA": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "JAM": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "JEY": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "JOR": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "JPN": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "KAZ": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "KEN": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "KGZ": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "KHM": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "KIR": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "KNA": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "KOR": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "KOS": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "KWT": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "LAO": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "LBN": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "LBR": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "LBY": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": True},
    "LCA": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "LIE": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "LKA": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "LSO": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "LTU": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "LUX": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "LVA": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "MAC": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "MAF": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "MAR": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "MCO": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "MDA": {"has_other_symbols": True, "has_cross": True, "has_star": True, "is_triband": True},
    "MDG": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "MDV": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "MEX": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "MHL": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "MKD": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "MLI": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "MLT": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "MMR": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "MNE": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "MNG": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "MNP": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "MOZ": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "MRT": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "MSR": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "MTQ": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "MUS": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "MWI": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "MYS": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "MYT": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "NAM": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "NCL": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "NER": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "NFK": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "NGA": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "NIC": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "NIU": {"has_other_symbols": False, "has_cross": True, "has_star": True, "is_triband": False},
    "NLD": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "NOR": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "NPL": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "NRU": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "NZL": {"has_other_symbols": False, "has_cross": True, "has_star": True, "is_triband": False},
    "OMN": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "PAK": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "PAN": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "PCN": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "PER": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "PHL": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "PLW": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "PNG": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "POL": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "PRI": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "PRK": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "PRT": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "PRY": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": True},
    "PSE": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "PYF": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "QAT": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "REU": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "ROU": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "RUS": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "RWA": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "SAU": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "SDN": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "SEN": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "SGP": {"has_other_symbols": True, "has_cross": True, "has_star": True, "is_triband": False},
    "SGS": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "SHN": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "SJM": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "SLB": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "SLE": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "SLV": {"has_other_symbols": True, "has_cross": True, "has_star": True, "is_triband": False},
    "SMR": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "SOM": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "SPM": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "SRB": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": True},
    "SSD": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "STP": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "SUR": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "SVK": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": True},
    "SVN": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": True},
    "SWE": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "SWZ": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "SXM": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "SYC": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "SYR": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "TCA": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "TCD": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "TGO": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "THA": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "TJK": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": True},
    "TKL": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "TKM": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "TLS": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "TON": {"has_other_symbols": False, "has_cross": True, "has_star": False, "is_triband": False},
    "TTO": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "TUN": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "TUR": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": False},
    "TUV": {"has_other_symbols": False, "has_cross": True, "has_star": True, "is_triband": False},
    "TWN": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "TZA": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "UGA": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "UKR": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "UMI": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "URY": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "USA": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "UZB": {"has_other_symbols": True, "has_cross": False, "has_star": True, "is_triband": True},
    "VAT": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "VCT": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "VEN": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": True},
    "VGB": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "VIR": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "VNM": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "VUT": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "WLF": {"has_other_symbols": True, "has_cross": True, "has_star": False, "is_triband": False},
    "WSM": {"has_other_symbols": False, "has_cross": False, "has_star": True, "is_triband": False},
    "YEM": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": True},
    "ZAF": {"has_other_symbols": False, "has_cross": False, "has_star": False, "is_triband": False},
    "ZMB": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False},
    "ZWE": {"has_other_symbols": True, "has_cross": False, "has_star": False, "is_triband": False}
}

tribands_details = {"AFG": {"vertical_triband": True}, "AND": {"vertical_triband": True},
                    "ARE": {"vertical_triband": False}, "ARG": {"vertical_triband": False},
                    "ARM": {"vertical_triband": False}, "AUT": {"vertical_triband": False},
                    "AZE": {"vertical_triband": False}, "BEL": {"vertical_triband": True},
                    "BGR": {"vertical_triband": False}, "BHS": {"vertical_triband": False},
                    "BLZ": {"vertical_triband": False}, "BOL": {"vertical_triband": False},
                    "BRB": {"vertical_triband": True}, "BWA": {"vertical_triband": False},
                    "CAN": {"vertical_triband": True}, "CIV": {"vertical_triband": True},
                    "CMR": {"vertical_triband": True}, "COL": {"vertical_triband": False},
                    "CUW": {"vertical_triband": False}, "DEU": {"vertical_triband": False},
                    "ECU": {"vertical_triband": False}, "EGY": {"vertical_triband": False},
                    "ESP": {"vertical_triband": False}, "EST": {"vertical_triband": False},
                    "ETH": {"vertical_triband": False}, "FRA": {"vertical_triband": True},
                    "GAB": {"vertical_triband": False}, "GHA": {"vertical_triband": False},
                    "GIN": {"vertical_triband": True}, "GMB": {"vertical_triband": False},
                    "GNQ": {"vertical_triband": False}, "GTM": {"vertical_triband": True},
                    "HND": {"vertical_triband": False}, "HRV": {"vertical_triband": False},
                    "HUN": {"vertical_triband": False}, "IND": {"vertical_triband": False},
                    "IRL": {"vertical_triband": True}, "IRN": {"vertical_triband": False},
                    "IRQ": {"vertical_triband": False}, "ITA": {"vertical_triband": True},
                    "JOR": {"vertical_triband": False}, "KEN": {"vertical_triband": False},
                    "KHM": {"vertical_triband": False}, "KWT": {"vertical_triband": False},
                    "LAO": {"vertical_triband": False}, "LBN": {"vertical_triband": False},
                    "LBY": {"vertical_triband": False}, "LSO": {"vertical_triband": False},
                    "LTU": {"vertical_triband": False}, "LVA": {"vertical_triband": False},
                    "LUX": {"vertical_triband": False}, "MDA": {"vertical_triband": True},
                    "MEX": {"vertical_triband": True}, "MLI": {"vertical_triband": True},
                    "MMR": {"vertical_triband": False}, "MNG": {"vertical_triband": True},
                    "MWI": {"vertical_triband": False}, "NCL": {"vertical_triband": False},
                    "NER": {"vertical_triband": False}, "NGA": {"vertical_triband": True},
                    "NIC": {"vertical_triband": False}, "NLD": {"vertical_triband": False},
                    "PER": {"vertical_triband": True}, "PRY": {"vertical_triband": False},
                    "PSE": {"vertical_triband": False}, "ROU": {"vertical_triband": True},
                    "RUS": {"vertical_triband": False}, "RWA": {"vertical_triband": False},
                    "SEN": {"vertical_triband": True}, "SLE": {"vertical_triband": False},
                    "SRB": {"vertical_triband": False}, "SVK": {"vertical_triband": False},
                    "SVN": {"vertical_triband": False}, "SYR": {"vertical_triband": False},
                    "TCD": {"vertical_triband": True}, "TJK": {"vertical_triband": False},
                    "UZB": {"vertical_triband": False}, "VEN": {"vertical_triband": False},
                    "YEM": {"vertical_triband": False}
                    }

special_questions = {
    1: {
        "question": "Is the first color (starting from top) yellow?",
        "countries": {
            "ECU": True,
            "SRB": False
        }
    },
    2: {
        "question": "Does the flag contain only one star?",
        "countries": {
            "AZE": True,
            "PRK": True,
            "UZB": False,
            "WSM": False,
            "USA": False,
            "LBR": True,
            "PAN": False,
            "PRI": True,
            "CHL": True
        }
    },
    3: {
        "question": "Is one of the parallel horizontal bars of a black color?",
        "countries": {
            "ARE": True,
            "KWT": False
        }
    },
    4: {
        "question": "Is the first color (starting from left) red?",
        "countries": {
            "GIN": True,
            "MLI": False
        }
    },
    5: {
        "question": "Is it the flag of Romania?",
        "countries": {
            "ROU": True,
            "TCD": False
        }
    },
    6: {
        "question": "Are the stars which are on the flag red?",
        "countries": {
            "NZL": True,
            "AUS": False
        }
    },
    7: {
        "question": "Is the first color (starting from top) red?",
        "countries": {
            "NLD": True,
            "RUS": False
        }
    },
    9: {
        "question": "Is the cross element on the flag red?",
        "countries": {
            "ISL": True,
            "NOR": False
        }
    },
    11: {
        "question": "Is the star element on the flag white?",
        "countries": {
            "TUR": True,
            "TUN": False
        }
    },
    14: {
        "question": "Are the cross elements on the flag red?",
        "countries": {
            "GEO": True,
            "DNK": False
        }
    },
    16: {
        "question": "Are there any hemicycles on the flag?",
        "countries": {
            "GRL": True,
            "IDN": False
        }
    }
}
